dustpath/web/forms/__init__.py
from .user import ProfileForm 
from .projects import ProjectForm


__all__ = [
    ProfileForm,
    ProjectForm, 
]

dustpath/web/forms/projects.py
from flask_wtf import FlaskForm
from wtforms import fields
# from wtforms.fields import html5
from wtforms import validators
from wtforms.widgets import TextInput

class ProjectForm(FlaskForm):
    name = fields.StringField('ชื่อโปรเจ็ค', validators=[validators.Length(min=1)])
    max_domain = fields.IntegerField('จำนวนโดเมน',
                                    default=1, 
                                    validators=[
                                        validators.InputRequired(),
                                        validators.NumberRange(min=1, message="จำนวนโดเมนน้อยเกินไป"),
                                    ])
    start_date = fields.DateField('วันที่เริ่มทำการคำนวณ',
                                    format='%d-%m-%Y',
                                    widget=TextInput())
    end_date = fields.DateField('วันที่ทำการคำนวณสิ้นสุด',
                                    format='%d-%m-%Y',
                                    widget=TextInput())

dustpath/web/forms/user.py
from flask_wtf import FlaskForm
from wtforms import fields
# from wtforms.fields import html5
from wtforms import validators

class ProfileForm(FlaskForm):
    firstname = fields.StringField('ชื่อ',
                                 validators=[validators.Length(min=1)])
    lastname = fields.StringField('นามสกุล',
                                validators=[validators.Length(min=1)])

dustpath/web/__init__.py
__version__ = "0.0.1"

from flask import Flask


from .. import models
from . import views
from . import nats

def create_app():
    app = Flask(__name__)
    app.config.from_object("dustpath.default_settings")
    app.config.from_envvar("DUSTPATH_SETTINGS", silent=True)

    models.init_db(app)
    views.register_blueprint(app)
    nats.init_nats(app)

    return app

dustpath/web/views/__init__.py
import datetime

from . import (
    domains,
    main,
    dashboard,
    projects,
    users,
    projects,
    )


def add_date_url(url):
    now = datetime.datetime.now()
    return f'{url}?date={now.strftime("%Y%m%d")}'


def get_subblueprints(views=[]):
    blueprints = []
    for view in views:
        blueprints.append(view.module)

        if "subviews" in dir(view):
            for module in get_subblueprints(view.subviews):
                if view.module.url_prefix and module.url_prefix:
                    module.url_prefix = view.module.url_prefix + module.url_prefix
                blueprints.append(module)

    return blueprints


def register_blueprint(app):
    app.add_template_filter(add_date_url)
    blueprints = get_subblueprints(
        [
            main,
            dashboard,
            users,
            domains,
            projects,
            projects,
        ])

    for blueprint in blueprints:
        app.register_blueprint(blueprint)

dustpath/web/views/dashboard.py
from flask import (Blueprint,
                   Flask,
                   redirect,
                   render_template,
                   url_for,
                   redirect)
from .. import models
import datetime
import mongoengine as me
import pathlib


module = Blueprint('dashboard', __name__, url_prefix='/dashboard')

@module.route('/')
def index():
    return render_template('main/dashboard.html')

dustpath/web/views/domains.py
from dustpath.models import domains
from flask import (Blueprint,
                   render_template,
                   redirect,
                   url_for,
                   request,
                   jsonify
                   )
import json, datetime
from flask_login import login_required
from .. import models

module = Blueprint('domains', __name__, url_prefix='/domains')

@module.route('/')
def index():
    domains = models.Domain.objects().order_by("-id")
    return render_template('domains/index.html',
                            domains=domains,)

@module.route('/record', methods=['GET', 'POST'])
def record():
    center = [7.0065949668769205, 100.49891880632555] # lat, long
    zoom = 10
    
    if request.method == 'POST':
        data = request.json
        if data:
            domain = models.Domain(center=data['center'], radius=data['radius'])
            domain.save()
            print(domain, "--------")
    return render_template('domains/record.html',
                           zoom=zoom,
                           center=center,)

dustpath/web/views/main.py
from flask import (Blueprint,
                   Flask,
                   redirect,
                   render_template,
                   url_for,
                   current_app,
                   redirect)
from .. import models
import datetime
import mongoengine as me

module = Blueprint('main', __name__, url_prefix='/')

@module.route('/')
def index():
    return render_template('main/landing.html')

dustpath/web/views/projects.py
from dustpath.models import projects
from flask import (
    Blueprint,
    render_template,
    redirect,
    request,
    url_for,
    Response,
    g,
    current_app,
    jsonify,
)
import datetime
from flask_login import login_required, current_user
import json
from dustpath import models
from dustpath.web import nats
from ..forms import ProjectForm

from .. import forms

module = Blueprint("projects", __name__, url_prefix="/projects")


@module.route('/')
def index():
    projects = models.Project.objects().order_by("-id")
    return render_template('projects/index.html',
                            projects=projects,)

@module.route('/record', methods=['GET', 'POST'])
def create():
    form = ProjectForm()
    if not form.validate_on_submit():
        return render_template('projects/create.html', form=form)
    project = models.Project(
        name=form.name.data,
    )
    project.wrf_config.max_domain = form.max_domain.data
    project.wrf_config.start_date = form.start_date.data
    project.wrf_config.end_date = form.end_date.data
    project.save()

    return redirect(url_for('projects.index'))
    
@module.route("/<project_id>/run_wrf", methods=["POST"])
def run_wrf(project_id):
    project_id = request.form.get("project_id")
    project = models.Project.objects.get(id=project_id)
    # if not project.is_assistant_or_owner(current_user._get_current_object()):
    #     return Response(403)

    # camera = models.Camera.objects.get(id=camera_id)
    data = {
        "action": "start-recorder",
        # "camera_id": camera_id,
        "project_id": project_id,
        # "user_id": str(current_user._get_current_object().id),
    }

    # if camera.motion_property.active:
    #     data["motion"] = camera.motion_property.active
    #     data["sensitivity"] = camera.motion_property.sensitivity

    nats.nats_client.publish("dustpath.processor.command", data)

    response = Response()
    response.status_code = 200
    return response

dustpath/web/views/users.py
from flask import (Blueprint, render_template,
                   url_for, redirect, request)
from flask_login import (login_required)
from dustpath import models
from ..forms import ProfileForm

module = Blueprint('users', __name__, url_prefix='/users')

@module.route('/record', methods=['GET', 'POST'])
def all_profile():
    user = models.User.objects().first()
    return render_template('users/profile.html', user=user)

@module.route('/record', methods=['GET', 'POST'])
def record():
    user_id = request.args.get('user_id')
    if user_id:
        user = models.User.objects.get(id=user_id)
        form = ProfileForm(obj=user)
    else:
        user = models.User()
        form = ProfileForm()
        
    if not form.validate_on_submit():
        return render_template('users/record.html', user=user,
                                                    form=form,)
    
    form.populate_obj(user)
    user.save()

    return redirect(url_for('users.record', user=user))

dustpath/web/templates/base/base-layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" media="all"
    href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') | add_date_url }}">

  <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') | add_date_url }}"></script>
  <script
    src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') | add_date_url }}"></script>

  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') | add_date_url }}">
  <link rel="icon" href="{{ url_for('static', filename='images/icon.png') }}">
  {% block additional_head %}{% endblock %}

  <title>{% block title %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
</head>

<body class="pusher">
  {% block body %}{% endblock body %}
  {% include "base/footer.html" %}
</body>

<script>
  $('.ui.dropdown')
    .dropdown();
  $(document)
    .ready(function () {
      $('.left.sidebar.menu')
        .sidebar('attach events', '.launch.icon.item', 'show')
        ;
    })
    ;
</script>

<style type="text/css">
  #link:hover {
    text-decoration: underline;
  }
</style>

{% block additional_js %}{% endblock %}

</html>

dustpath/web/templates/base/base-map.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        #mapid { 
            height: 60rem;
            background-color:white;
        }
        #back_btt{
            position: absolute; 
            margin: 9px;
            padding: 10px;
            width: 80px; 
            background-color: #ffffff; 
            border-radius: 10%;
            font-size: 30px; 
            text-align: center; 
            z-index: 10;
          }
    </style>
    <title>{% block title  %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') }}">
    <script src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/brython/brython.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/brython/brython_stdlib.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.css') }}" />
    <script src="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/leaflet-draw/dist/leaflet.draw.css') }}" />
    <script src="{{ url_for('static', filename='node_modules/leaflet-draw/dist/leaflet.draw.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/leaflet-geometryutil/src/leaflet.geometryutil.js') }}"></script>
</head>

<body onload="brython()">
    {% block body %}{% endblock %}
</body>
</html>

dustpath/web/templates/base/default-page.html
{% extends "/base/base-layout.html" %}
{% block body %}

{% include "base/navbar.html" %}
<div class="ui vertical inverted sidebar">
  {% include "base/sidebar.html" %}
</div>

<div class="ui fixed main menu">
  <a class="launch icon item">
    <i class="content icon"></i>
  </a>
  <div class="item">
    <a id="link" href="/" style="color: black;">
      Dustpath
    </a>
  </div>
</div>

<div class="pusher" style="min-height: 84% !important;">
  <main class="twelve wide column" style="padding-top: 3em;">
    {% block content %}{% endblock content %}
  </main>
</div>

<script>
  var dropdown = document.getElementsByClassName("ui item secondary");
  var i;

  for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function () {
      this.classList.toggle("active");
      var dropdownContent = this.nextElementSibling;
      if (dropdownContent.style.display === "block") {
        dropdownContent.style.display = "none";
      } else {
        dropdownContent.style.display = "block";
      }
    });
  }
  if (screen.width <= 699) {
    document.getElementById("content-desktop");
  }
</script>
{% endblock %}

dustpath/web/templates/base/footer.html
<style>
  a:link {
    color: white;
    background-color: transparent;
    text-decoration: none;
  }

  a:visited {
    color: white;
    background-color: transparent;
    text-decoration: none;
  }

  a:hover {
    color: gray;
    background-color: transparent;
    text-decoration: underline;
  }
</style>
<footer>
  <div class="ui inverted vertical footer segment">
    <div class="ui center aligned container">
      <div class="ui stackable inverted grid">
        <div class="six wide column">
          <br>
          <img src="{{ url_for('static', filename='images/icon.png') }}" class="ui centered tiny image">
          <br>
          ทางของฝุ่น<br> ระบบจำลองการเคลื่อนตัวของฝุ่น PM 2.5
        </div>
        <div class="four wide column">
          <br>
          <b>ผู้จัดทำ</b><br> 1. นายพงศธร ชดช้อย<br> 2. นายทิวัตถ์ ลิม<br> 3. นายธีรยุทธ นุชผดุง<br><br>
          <b>ที่ปรึกษาโครงการ</b><br>ดร.ธนาธิป ลิ่มนา
        </div>
        <div class="six wide column">
          <br>
          <a href="http://www.coe.psu.ac.th" class="item inverted" target="_blank">
            <img src="{{ url_for('static', filename='images/coe.png') }}" class="ui centered tiny image">
            <br>
            สาขาวิชาวิศวกรรมคอมพิวเตอร์<br>
            คณะวิศวกรรมศาสตร์
            มหาวิทยาลัยสงขลานครินทร์<br>
            <br>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

dustpath/web/templates/base/navbar.html
<div class="ui fixed main menu">
    <a class="launch icon item">
        <i class="content icon"></i>
    </a>
    <div class="item">
        <a id="link" href="/" style="color: black;">
            Dustpath
        </a>
    </div>
</div>

dustpath/web/templates/base/sidebar.html
<div class="ui vertical inverted sidebar large menu left">
  <div class="item">
    <span style="font-size: 24px">{{ config['APP_TITLE'] }}</span>
  </div>
  <div class="item">
    <a href="{{ url_for('dashboard.index') }}" class="header" style="text-decoration: none;">
      <i class="home icon"></i>
      หน้าหลัก
    </a>
  </div>
  <div class="item">
    <a class="header">
      <i class="map icon"></i>
      แผนที่
    </a>
    <div class="menu">
      <a href="{{ url_for('domains.index') }}" class="item">
        <i class="map icon"></i>โดเมนทั้งหมด
      </a>
      <a href="{{ url_for('domains.record') }}" class="item">
        <i class="map marker alternate icon"></i>บันทึกโดเมน
      </a>
    </div>
  </div>
  <div class="item">
    <a href="{{ url_for('users.record') }}" class="header" style="text-decoration: none;">
      <i class="user icon"></i>
      โปรไฟล์
    </a>
  </div>
  <div class="item">
    <a href="{{ url_for('projects.create') }}" class="header" style="text-decoration: none;">
      <i class="cog icon"></i>
      CreateProject
    </a>
  </div>
</div>

dustpath/web/templates/compile/index.html
{% extends "base/default-page.html" %}
{% block title %}
คอมไพล์ | {{ config.get('APP_TITLE') }}
{% endblock %}
{% block content %}
<div class="ui vertical masthead segment">
  <div class="ui padding-left aligned container" style="margin-bottom: 1%;">
    <div class="ui teal clearing segment" style="margin-top: 7%;margin-bottom:25%;">
      <div class="ui left aligned container" style="margin-bottom: 1%;">
        <h1 style="color: rgb(0, 0, 0);left: 50%;">
          คอมไพล์
        </h1>
      </div>
    </div>
  </div>
</div>

{% endblock %}

dustpath/web/templates/domains/index.html
{% extends "base/default-page.html" %}
{% block content %}
<div class="pusher">
  <div class="ui vertical masthead segment" style="background-color: rgba(242,245,245,0.8)">
    <div class="ui container">
      <div class="ui teal segment" style="margin-top:7%;margin-bottom:100%;">
        <h1>
          โดเมนทั้งหมด
        </h1>
        <div class="ui divider">
        </div>
        <div class="ui bottom attached tab segment active" data-tab="first">
          <div class="ui">
            <table id="mytable" class="ui teal celled table">
              <thead>
                <tr>
                  <th>Center[Lat, Long]</th>
                  <th>Radius</th>
                  <th>xx</th>
                </tr>
              </thead>
              <tbody>
                {% for domain in domains %}
                <tr>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content" id="namelist" style="color: black;">
                        {{ domain.center[0] }} {{domain.center[1]}}
                      </a>
                    </div>
                  </td>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content"  style="color: black;">
                        {{ domain.radius }}
                      </a>
                    </div>
                  </td>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content" href="{{ url_for('domains.record') }}">
                        Show
                      </a>
                    </div>
                  </td>
                </tr>
                {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

dustpath/web/templates/domains/record.html
{% extends '/base/base-map.html' %}
{% block body %}
<div class="ui vertical masthead segment" style="background-color: cornsilk;width: 100%; height: 100%;">
    <div id="mapid" style="z-index:1;"></div>
    <div align="right" style="margin-top:2em;z-index: 2;position: absolute;
                              top: 100px;right: 10px;;padding: 5px">
        <button id="record" class="ui teal button" style="margin-top:5px">
            บันทึก</button>
    </div>
</div>

<script type="text/python">
from browser import document, window, ajax
import javascript as js
import datetime
import json


# Access the leaflet.js API
leaflet = window.L

openstreet = leaflet.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    "maxZoom": 19,
	"attribution": '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
})

center = {{center}}
zoom = {{zoom}}
map = leaflet.map('mapid', {
    'center': center,
    'zoom': zoom,
    'layers': openstreet
})
drawnItems = leaflet.FeatureGroup.new()
map.addLayer(drawnItems)
drawControl = leaflet.Control.Draw.new({
         'edit': {
             'featureGroup': drawnItems
         }
})

map.addControl(drawControl)

#จำเป็นต้องใช้กรุ๊ปเพราะจำเป็นต้องใช้ต่อและไม่สามารถอ้างอิงก่อนจะ assign ภายในฟังก์ชันได้
circle_layers = leaflet.layerGroup([])

def save_data(e):
    layers = circle_layers.getLayers()
    if layers:
        layer = layers[0]
        latlng = layer.getLatLng()
        layer_center = [latlng.lat, latlng.lng]
        layer_radius = layer.getRadius()
        
        req = ajax.ajax()
        req.open('POST', '/domains/record', True)
        req.set_header('content-type', 'application/json')
        data = json.dumps(
            {'center': layer_center,
            'radius': layer_radius}
        )
        req.send(data)
        print("data was saved")

def create_circle(e):
    if e.layerType == 'circle':
        layer = e.layer
        latlng = layer.getLatLng()
        layer_center = [latlng.lat, latlng.lng]
        layer_radius = layer.getRadius()
        circle_layer = leaflet.circle(layer_center, {'radius': layer_radius})
        circle_layers.clearLayers()
        circle_layers.addLayer(circle_layer)
        circle_layers.addTo(map)
        
map.on('draw:created', create_circle)
document["record"].bind("click", save_data)

</script>
{% endblock %}

dustpath/web/templates/main/dashboard.html
{% extends "base/default-page.html" %}
{% block title %}
หน้าหลัก | {{ config.get('APP_TITLE') }}
{% endblock %}
{% block content %}
<div class="ui vertical masthead segment">
  <div class="ui padding-left aligned container" style="margin-bottom: 1%;">
    <div class="ui teal clearing segment" style="margin-top: 7%;margin-bottom:25%;">
      <div class="ui left aligned container" style="margin-bottom: 1%;">
        <h1>
          <h1 style="color: rgb(0, 0, 0);left: 50%;">
            หน้าหลัก
          </h1>
        </h1>
        
      </div>
      <a class="ui primary icon top right pointing big button" href="{{url_for('compile.index')}}">
        <i class="sign in alternate icon"></i>
        <span class="text">เริ่มการคอมไพล์</span>
      </a>
    </div>
  </div>
</div>    
{% endblock %}

dustpath/web/templates/main/landing.html
{% extends "base/default-page.html" %}
{% block content %}
<div class="header1">
  <div class="title center">
    <h1>ยินดีต้อนรับสู่ ทางของฝุ่น</h1>
    <h3>Welcome to Dustpath Application</h3>
    <h3>ระบบจำลองการเคลื่อนตัวของฝุ่น PM 2.5</h3>
    <br>
      <a class="ui primary icon top right pointing big button" href="{{url_for('dashboard.index')}}">
        <i class="sign in alternate icon"></i>
        <span class="text">เข้าสู่หน้าหลัก</span>
      </a>
  </div>
</div>
{% endblock %}

dustpath/web/templates/projects/create.html
{% extends "base/default-page.html" %}
{% macro render_calendar(field, calendar_id='calendar') -%}
<div class="ui calendar" id="{{ calendar_id }}">
  <div class="ui input left icon">
    <i class="calendar icon"></i>
    {% if field.data %}
    {{ field(autocomplete='off',value=field.data.strftime('%d-%m-%Y')) }}
    {% else %} {{ field(autocomplete='off') }}
    {% endif %}
  </div>
</div>
{%- endmacro %}
{% block content %}
<div class="ui container">
  <div class="ui one column stackable grid">
    <div class="column harvers" style="padding-top: 0;">
      <div style="margin-top: 3rem;">
        <h1 class="ui centered header">ตั้งค่า</h1>
      </div>
      <h4 class="ui horizontal divider header">
        ตั้งค่าการจำลองสภาพการเคลื่อนที่
      </h4>
      <div class="ui vertical segment">
        <form class="ui form error" enctype="multipart/form-data" method="POST">
          {{ form.csrf_token }}
          <div class="field">
            {{ form.name.label }}
            {{ form.name }}
            {% for error in form.name.errors %}
            <p style="color: red;">* โปรดระบุจำนวนโดเมนสูงสุด</p>
            {% endfor %}
          </div>
          <div class="field">
            {{ form.max_domain.label }}
            {{ form.max_domain }}
            {% for error in form.max_domain.errors %}
            <p style="color: red;">* โปรดระบุจำนวนโดเมนสูงสุด</p>
            {% endfor %}
          </div>
          <div class="two fields">
            <div class="required eight wide field">
              <h3>{{ form.start_date.label }}</h3>
              {{ render_calendar(form.start_date,
              calendar_id="start_date_calendar") }}
              {% for error in form.start_date.errors %}
              <p style="color: red;">* โปรดใส่วันที่เริ่มการคำนวณ</p>
              {% endfor %}
            </div>
            <div class="required eight wide field">
              <h3>{{ form.end_date.label }}</h3>
              {{ render_calendar(form.end_date,
              calendar_id="end_date_calendar") }}
              {% for error in form.end_date.errors %}
              <p style="color: red;">* โปรดใส่วันที่สิ้นสุดการคำนวณ</p>
              {% endfor %}
            </div>
          </div>  
          <button class="ui right floated button green" type="submit">ยืนยัน</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
  datetime_formatter = {
    datetime: function (datetime, settings) {
      if (!datetime) return '';
      var day = datetime.getDate();
      var month = datetime.getMonth() + 1;
      var year = datetime.getFullYear();
      var hour = datetime.getHours();
      var minute = datetime.getMinutes();
      return ("0" + day).slice(-2) + '-' + ("0" + month).slice(-2) + '-' + year;
    }
  };


  var calendar_setting = {
    type: 'date',
    monthFirst: false,
    formatter: datetime_formatter,
    text: {
      days: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],
      months: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤษจิกายน', 'ธันวาคม'],
      monthsShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],
      today: 'วันนี้',
      now: 'ปัจจุบัน',
      am: 'AM',
      pm: 'PM'
    }
  };

  $('.ui.calendar').calendar(calendar_setting);




</script>
{% endblock %}

dustpath/web/templates/projects/index.html
{% extends "base/default-page.html" %}
{% block content %}
<div class="pusher">
  <div class="ui vertical masthead segment" style="background-color: rgba(242,245,245,0.8)">
    <div class="ui container">
      <div class="ui teal segment" style="margin-top:7%;margin-bottom:100%;">
        <h1>
          WRF Configuration
        </h1>
        <div class="ui divider">
        </div>
        <div class="ui bottom attached tab segment active" data-tab="first">
          <div class="ui">
            <table id="mytable" class="ui teal celled table">
              <thead>
                <tr>
                  <th>name</th>
                  <th>start_date</th>
                  <th>end_date</th>
                  <th>max_domain</th>
                </tr>
              </thead>
              <tbody>
                {% for project in projects %}
                <tr>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content" id="namelist" style="color: black;">
                        {{ project.name }}
                      </a>
                    </div>
                  </td>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content" id="namelist" style="color: black;">
                        {{ project.wrf_config.start_date }}
                      </a>
                    </div>
                  </td>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content"  style="color: black;">
                        {{ project.wrf_config.end_date }}
                      </a>
                    </div>
                  </td>
                  <td>
                    {{ project.wrf_config.max_domain }}
                  </td>
                </tr>
                {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

dustpath/web/templates/users/profile.html
{% extends "base/default-page.html" %}
{% block content %}

<div class="ui vertical masthead segment" style="background-color:rgba(242,245,245,0.8)">
  <div class="ui padding-left aligned container" style="margin-bottom: 1%;">
    <div class="ui teal clearing segment" style="margin-top: 7%;margin-bottom:25%;">
      <div class="ui left aligned container" style="margin-bottom: 1%;">
        <h1>
          <h1 style="color: rgb(0, 0, 0);left: 50%;">
            ข้อมูล
            <span style="color: red;">
              {{ user.firstname }}
              {{ user.lastname }}
            </span>
          </h1>
        </h1>
      </div>
    </div>
  </div>
</div>    
{% endblock %}

dustpath/web/templates/users/record.html
{% extends "base/default-page.html" %}
{% block content %}

<div class="ui vertical masthead segment" style="background-color:rgba(242,245,245,0.8)">
  <div class="ui padding-left aligned container" style="margin-bottom: 1%;">
    <div class="ui teal clearing segment" style="margin-top: 7%;margin-bottom:25%;">
      <div class="ui left aligned container" style="margin-bottom: 1%;">
        <h1>
          <h1 style="color: rgb(0, 0, 0);left: 50%;">
            ข้อมูล
            <form class="ui form" action='' method="POST" style="width: 90%; left:5% ;" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <h1>
                  แก้ไขข้อมูล
                </h1>
                <div class="ui divider"></div>
                <div class="field">
                  <h3 class="ui header">ข้อมูลส่วนตัว</h3>
                </div>
                <div class="two fields">
                  <div class="field">
                    {{ form.firstname.label }}
                    {{ form.firstname }}
                    {% for error in form.lastname.errors %}
                    <p style="color: red;">* โปรดใส่</p>
                    {% endfor %}
                  </div>
                  <div class="field">
                    {{ form.lastname.label }}
                    {{ form.lastname }}
                    {% for error in form.lastname.errors %}
                    <p style="color: red;">* โปรดใส่</p>
                    {% endfor %}
                  </div>
                </div>
                <a href="{{ url_for('users.record')}}" target="_blank">
                  <button class="ui teal button" type="submit" style="right: 0%;">
                    <div class="visible content">ยืนยัน</div>
                  </button>
                </a>
            </form>
          </h1>
        </h1>
      </div>
    </div>
  </div>
</div>    
{% endblock %}